# Generated by Django 5.2.4 on 2025-08-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_books', 'Can view books'), ('can_create_books', 'Can create books'), ('can_edit_books', 'Can edit books'), ('can_delete_books', 'Can delete books')]},
        ),
    ]
